import type {
  QuickSummaryContent,
  DeepSummaryContent,
  ActionItem,
  ChronologicalSection,
} from '@/types/database';

interface SummaryToMarkdownOptions {
  episodeTitle: string;
  podcastName: string;
  publishedAt?: string | null;
  durationSeconds?: number | null;
  quickSummary?: QuickSummaryContent | null;
  deepSummary?: DeepSummaryContent | null;
  url?: string;
}

/**
 * Converts summary data into clean Markdown for Obsidian/Notion/any markdown tool.
 * Uses section_labels when present (Hebrew episodes get Hebrew headers).
 */
export function summaryToMarkdown(opts: SummaryToMarkdownOptions): string {
  const {
    episodeTitle,
    podcastName,
    publishedAt,
    durationSeconds,
    quickSummary,
    deepSummary,
    url,
  } = opts;

  const lines: string[] = [];

  // ── Header ──
  lines.push(`# ${episodeTitle}`);
  const meta: string[] = [`**${podcastName}**`];
  if (publishedAt) {
    meta.push(formatDate(publishedAt));
  }
  if (durationSeconds) {
    meta.push(formatDuration(durationSeconds));
  }
  lines.push(meta.join(' | '));
  lines.push('');

  // ── Quick Summary ──
  if (quickSummary) {
    if (quickSummary.hook_headline) {
      lines.push(`## Hook`);
      lines.push(quickSummary.hook_headline);
      lines.push('');
    }

    if (quickSummary.executive_brief) {
      lines.push(`## Executive Brief`);
      lines.push(quickSummary.executive_brief);
      lines.push('');
    }

    if (quickSummary.golden_nugget) {
      lines.push(`## Golden Nugget`);
      lines.push(`> ${quickSummary.golden_nugget}`);
      lines.push('');
    }

    if (quickSummary.perfect_for) {
      lines.push(`**Perfect for:** ${quickSummary.perfect_for}`);
      lines.push('');
    }

    if (quickSummary.tags?.length) {
      lines.push(`**Tags:** ${quickSummary.tags.join(', ')}`);
      lines.push('');
    }
  }

  // ── Deep Summary ──
  if (deepSummary) {
    const labels = deepSummary.section_labels;

    // Separator between quick and deep
    if (quickSummary) {
      lines.push('---');
      lines.push('');
    }

    // Overview
    if (deepSummary.comprehensive_overview) {
      lines.push(`## ${labels?.comprehensive_overview || 'Overview'}`);
      // Strip <<highlight>> markers for plain markdown
      lines.push(deepSummary.comprehensive_overview.replace(/<<|>>/g, ''));
      lines.push('');
    }

    // Core Concepts
    if (deepSummary.core_concepts?.length) {
      lines.push(`## ${labels?.core_concepts || 'Core Concepts'}`);
      for (const concept of deepSummary.core_concepts) {
        lines.push(`### ${concept.concept}`);
        lines.push(concept.explanation);
        if (concept.quote_reference) {
          lines.push(`> "${concept.quote_reference}"`);
        }
        lines.push('');
      }
    }

    // Episode Flow (chronological breakdown)
    if (deepSummary.chronological_breakdown?.length) {
      lines.push(`## ${labels?.episode_flow || 'Episode Flow'}`);
      for (const section of deepSummary.chronological_breakdown) {
        const title = formatChronologicalTitle(section);
        lines.push(`### ${title}`);
        lines.push(section.content);
        lines.push('');
      }
    }

    // Contrarian Views / Counterpoints
    if (deepSummary.contrarian_views?.length) {
      lines.push(`## ${labels?.counterpoints || 'Counterpoints'}`);
      for (const view of deepSummary.contrarian_views) {
        lines.push(`- ${view}`);
      }
      lines.push('');
    }

    // Action Items
    if (deepSummary.actionable_takeaways?.length) {
      lines.push(`## ${labels?.actionable_takeaways || 'Action Items'}`);
      for (const item of deepSummary.actionable_takeaways) {
        if (typeof item === 'string') {
          lines.push(`- [ ] ${item}`);
        } else {
          const actionItem = item as ActionItem;
          const suffix = [actionItem.category, actionItem.priority]
            .filter(Boolean)
            .join(', ');
          lines.push(`- [ ] ${actionItem.text}${suffix ? ` (${suffix})` : ''}`);
        }
      }
      lines.push('');
    }
  }

  // ── Footer ──
  lines.push('---');
  if (url) {
    lines.push(`*Generated by Yedapo · [View online](${url})*`);
  } else {
    lines.push(`*Generated by Yedapo*`);
  }

  return lines.join('\n');
}

// ── Helpers ──

function formatDate(dateString: string): string {
  try {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return dateString;
  }
}

function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  if (hours > 0) {
    return `${hours}h ${minutes}m`;
  }
  return `${minutes}m`;
}

function formatChronologicalTitle(section: ChronologicalSection): string {
  const parts: string[] = [];
  if (section.timestamp) {
    parts.push(section.timestamp);
  }
  if (section.title) {
    parts.push(section.title);
  } else if (section.timestamp_description) {
    parts.push(section.timestamp_description);
  }
  return parts.join(' — ') || 'Section';
}
