import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service - Yedapo",
  description: "Yedapo Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen pb-20">
      <div className="max-w-2xl mx-auto px-4 pt-8 space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-foreground tracking-tight">Terms of Service</h1>
          <p className="text-muted-foreground mt-1">Last updated: March 28, 2026</p>
        </div>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By accessing or using Yedapo (&quot;the Service&quot;), operated by Yedapo, Tel Aviv, Israel,
            you agree to be bound by these Terms of Service.
            If you do not agree with any part of these terms, you may not use the Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Yedapo is an AI-powered podcast companion tool that provides AI-generated summaries, highlights,
            shownotes, keywords, and transcripts for podcast episodes and YouTube content. The Service is designed
            to help users discover, preview, and engage more deeply with podcast content.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">3. AI-Generated Content Disclaimer</h2>
          <div className="rounded-lg border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-900/10 p-4">
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong className="text-foreground">Important:</strong> Summaries, highlights, shownotes, keywords,
              and other analytical content displayed on Yedapo are generated by artificial intelligence (AI) models.
              This content may contain inaccuracies, misinterpretations, or omissions. AI-generated content does not
              represent the views or endorsements of the original content creators, Yedapo, or its affiliates.
            </p>
          </div>
          <p className="text-sm text-muted-foreground leading-relaxed">
            AI-generated summaries and analyses are provided as supplementary tools to help users preview and engage
            with content. They are not intended to replace the original podcast episodes or videos. We encourage users
            to listen to the original content for the full experience.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">4. Fair Use & Copyright</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Yedapo provides transformative, AI-generated analyses of publicly available podcast and video content.
            Our summaries and insights are designed to help users discover and preview content, not to substitute
            for the original works. All original content remains the property of its respective creators and publishers.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            If you are a content creator and believe your rights are being infringed, please review our{' '}
            <Link href="/dmca" className="text-primary hover:underline">DMCA & Takedown Policy</Link>.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">5. User Accounts</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You may need to create an account to access certain features. You are responsible for maintaining
            the confidentiality of your account credentials and for all activity that occurs under your account.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">6. Acceptable Use</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to the Service or its systems</li>
            <li>Redistribute AI-generated content as your own original work</li>
            <li>Use automated tools to scrape or bulk-download content from the Service</li>
            <li>Circumvent rate limits or usage quotas</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">7. Rate Limits & Quotas</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The Service enforces usage limits including rate limiting and daily quotas for AI-powered features
            such as &quot;Ask AI.&quot; These limits are subject to change. Exceeding these limits may result in
            temporary restrictions on your access to certain features.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">8. Third-Party Services</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Yedapo integrates with third-party services including podcast directories, analytics providers,
            and AI model providers. Your use of the Service may be subject to the terms and policies of these
            third-party providers. Yedapo is not responsible for the availability or accuracy of third-party services.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">9. Limitation of Liability</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The Service is provided &quot;as is&quot; without warranties of any kind. Yedapo shall not be liable
            for any indirect, incidental, special, or consequential damages arising from your use of the Service,
            including any reliance on AI-generated content.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">10. Age Requirement</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You must be at least 13 years old (or 16 in the European Economic Area) to use Yedapo.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">11. Intellectual Property</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            AI-generated summaries are provided for personal, non-commercial use. You may not redistribute,
            sell, or commercially exploit AI-generated content from Yedapo.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">12. Repeat Infringer Policy</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            In accordance with the DMCA, we will terminate accounts of users who are repeat copyright infringers.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">13. Termination</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We reserve the right to suspend or terminate your account at any time for violation of these Terms,
            with or without notice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">14. Indemnification</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You agree to indemnify and hold harmless Yedapo and its operators from any claims arising from
            your use of the service or violation of these Terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">15. Dispute Resolution</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We encourage you to contact us at{' '}
            <a href="mailto:legal@yedapo.com" className="text-primary hover:underline">legal@yedapo.com</a>{' '}
            before initiating any formal proceedings. We will attempt to resolve disputes informally within 30 days.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">16. Governing Law</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            These Terms are governed by the laws of the State of Israel. Any disputes shall be resolved in the
            courts of Tel Aviv, Israel.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">17. Changes to Terms</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We reserve the right to modify these terms at any time. Material changes will be communicated through
            the Service. Continued use after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">18. Contact</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            For questions about these Terms, contact us at{' '}
            <a href="mailto:legal@yedapo.com" className="text-primary hover:underline">legal@yedapo.com</a>.
          </p>
        </section>

        <div className="pt-4 border-t border-border pb-8">
          <div className="text-xs text-muted-foreground space-y-1">
            <p className="font-medium text-foreground">Yedapo</p>
            <p>Tel Aviv, Israel</p>
            <p>
              <a href="mailto:support@yedapo.com" className="text-primary hover:underline">support@yedapo.com</a>
            </p>
          </div>
          <p className="text-xs text-muted-foreground mt-3">
            See also: <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>{" "}
            and <Link href="/refund" className="text-primary hover:underline">Refund Policy</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
