import { describe, it, expect } from 'vitest';
import { summaryToMarkdown } from '../summary-to-markdown';
import type { QuickSummaryContent, DeepSummaryContent, ActionItem } from '@/types/database';

const BASE_OPTS = {
  episodeTitle: 'How to Build a Startup',
  podcastName: 'Startup FM',
  publishedAt: '2026-03-10T00:00:00Z',
  durationSeconds: 3600,
  url: 'https://yedapo.com/episode/123/insights',
};

const QUICK: QuickSummaryContent = {
  hook_headline: 'The one thing every founder gets wrong',
  executive_brief: 'In this episode, the host discusses the top 5 mistakes founders make.',
  golden_nugget: 'Revenue is vanity, profit is sanity, cash is reality.',
  perfect_for: 'First-time founders and aspiring entrepreneurs',
  tags: ['startup', 'founder', 'growth'],
};

const DEEP: DeepSummaryContent = {
  comprehensive_overview: 'This is a <<comprehensive>> overview of the episode discussing startup fundamentals.',
  core_concepts: [
    {
      concept: 'Product-Market Fit',
      explanation: 'Finding the right market for your product is crucial.',
      quote_reference: 'Build something people want.',
    },
    {
      concept: 'Lean Methodology',
      explanation: 'Start small, iterate fast.',
    },
  ],
  chronological_breakdown: [
    {
      timestamp: '00:00',
      timestamp_seconds: 0,
      title: 'Introduction',
      content: 'The host introduces the topic.',
    },
    {
      timestamp: '15:30',
      timestamp_seconds: 930,
      title: 'Deep Dive',
      content: 'Detailed discussion of startup challenges.',
    },
  ],
  contrarian_views: [
    'Some argue that planning is overrated.',
    'Others believe speed is more important than quality.',
  ],
  actionable_takeaways: [
    'Talk to 100 customers before building',
    {
      text: 'Set up analytics from day one',
      category: 'tool',
      priority: 'high',
    } as ActionItem,
    {
      text: 'Read The Lean Startup',
      category: 'resource',
    } as ActionItem,
  ],
};

describe('summaryToMarkdown', () => {
  it('renders quick summary only', () => {
    const md = summaryToMarkdown({ ...BASE_OPTS, quickSummary: QUICK });

    expect(md).toContain('# How to Build a Startup');
    expect(md).toContain('**Startup FM**');
    expect(md).toContain('Mar 10, 2026');
    expect(md).toContain('1h 0m');
    expect(md).toContain('## Hook');
    expect(md).toContain('The one thing every founder gets wrong');
    expect(md).toContain('## Executive Brief');
    expect(md).toContain('## Golden Nugget');
    expect(md).toContain('> Revenue is vanity');
    expect(md).toContain('**Perfect for:** First-time founders');
    expect(md).toContain('**Tags:** startup, founder, growth');
    expect(md).toContain('Generated by Yedapo');
    // Should NOT contain deep sections
    expect(md).not.toContain('## Overview');
    expect(md).not.toContain('## Core Concepts');
  });

  it('renders deep summary only', () => {
    const md = summaryToMarkdown({ ...BASE_OPTS, deepSummary: DEEP });

    expect(md).toContain('## Overview');
    expect(md).toContain('comprehensive overview');
    // Highlight markers should be stripped
    expect(md).not.toContain('<<');
    expect(md).not.toContain('>>');
    expect(md).toContain('## Core Concepts');
    expect(md).toContain('### Product-Market Fit');
    expect(md).toContain('> "Build something people want."');
    expect(md).toContain('### Lean Methodology');
    expect(md).toContain('## Episode Flow');
    expect(md).toContain('### 00:00 — Introduction');
    expect(md).toContain('### 15:30 — Deep Dive');
    expect(md).toContain('## Counterpoints');
    expect(md).toContain('- Some argue that planning is overrated.');
    expect(md).toContain('## Action Items');
    expect(md).toContain('- [ ] Talk to 100 customers before building');
    // Should NOT contain quick sections
    expect(md).not.toContain('## Hook');
    expect(md).not.toContain('## Executive Brief');
  });

  it('renders both quick + deep with separator', () => {
    const md = summaryToMarkdown({ ...BASE_OPTS, quickSummary: QUICK, deepSummary: DEEP });

    // Should have both sections
    expect(md).toContain('## Hook');
    expect(md).toContain('## Overview');
    // Separator between quick and deep
    const hookIdx = md.indexOf('## Hook');
    const overviewIdx = md.indexOf('## Overview');
    const separatorIdx = md.indexOf('---', hookIdx);
    expect(separatorIdx).toBeGreaterThan(hookIdx);
    expect(separatorIdx).toBeLessThan(overviewIdx);
  });

  it('uses section_labels for Hebrew content', () => {
    const hebrewDeep: DeepSummaryContent = {
      ...DEEP,
      section_labels: {
        comprehensive_overview: 'סקירה מקיפה',
        core_concepts: 'מושגי ליבה',
        episode_flow: 'מהלך הפרק',
        counterpoints: 'נקודות נגד',
        actionable_takeaways: 'פריטי פעולה',
        counterpoints_subtitle: 'נקודות למחשבה',
        transcript: 'תמלול',
        action_items: 'פריטי פעולה',
        discussion: 'דיון',
      },
    };

    const md = summaryToMarkdown({ ...BASE_OPTS, deepSummary: hebrewDeep });

    expect(md).toContain('## סקירה מקיפה');
    expect(md).toContain('## מושגי ליבה');
    expect(md).toContain('## מהלך הפרק');
    expect(md).toContain('## נקודות נגד');
    expect(md).toContain('## פריטי פעולה');
    // Should NOT use English defaults
    expect(md).not.toContain('## Overview');
    expect(md).not.toContain('## Core Concepts');
  });

  it('handles empty/null fields gracefully', () => {
    const emptyQuick: QuickSummaryContent = {
      hook_headline: '',
      executive_brief: '',
      golden_nugget: '',
      perfect_for: '',
      tags: [],
    };

    // Should not throw
    const md = summaryToMarkdown({
      episodeTitle: 'Test Episode',
      podcastName: 'Test Podcast',
      quickSummary: emptyQuick,
    });

    expect(md).toContain('# Test Episode');
    expect(md).toContain('**Test Podcast**');
    // Empty fields should not produce section headers
    expect(md).not.toContain('## Hook');
    expect(md).not.toContain('## Executive Brief');
    expect(md).not.toContain('## Golden Nugget');
    expect(md).not.toContain('**Tags:**');
  });

  it('handles null summaries without crashing', () => {
    const md = summaryToMarkdown({
      episodeTitle: 'Bare Episode',
      podcastName: 'Bare Podcast',
    });

    expect(md).toContain('# Bare Episode');
    expect(md).toContain('**Bare Podcast**');
    expect(md).toContain('Generated by Yedapo');
  });

  it('renders ActionItem objects with category and priority', () => {
    const deepWithActions: DeepSummaryContent = {
      comprehensive_overview: '',
      core_concepts: [],
      chronological_breakdown: [],
      contrarian_views: [],
      actionable_takeaways: [
        {
          text: 'Install PostHog',
          category: 'tool',
          priority: 'high',
        } as ActionItem,
        {
          text: 'Read Crossing the Chasm',
          category: 'resource',
        } as ActionItem,
        'Simple string takeaway',
      ],
    };

    const md = summaryToMarkdown({ ...BASE_OPTS, deepSummary: deepWithActions });

    expect(md).toContain('- [ ] Install PostHog (tool, high)');
    expect(md).toContain('- [ ] Read Crossing the Chasm (resource)');
    expect(md).toContain('- [ ] Simple string takeaway');
  });

  it('renders URL in footer when provided', () => {
    const md = summaryToMarkdown({ ...BASE_OPTS, quickSummary: QUICK });
    expect(md).toContain('[View online](https://yedapo.com/episode/123/insights)');
  });

  it('omits URL from footer when not provided', () => {
    const md = summaryToMarkdown({
      episodeTitle: 'Test',
      podcastName: 'Pod',
      quickSummary: QUICK,
    });
    expect(md).not.toContain('[View online]');
    expect(md).toContain('*Generated by Yedapo*');
  });

  it('handles chronological sections with legacy timestamp_description', () => {
    const deepLegacy: DeepSummaryContent = {
      comprehensive_overview: 'Overview',
      core_concepts: [],
      chronological_breakdown: [
        {
          timestamp_description: 'The Opening Argument',
          content: 'Discussion begins here.',
        },
      ],
      contrarian_views: [],
      actionable_takeaways: [],
    };

    const md = summaryToMarkdown({ ...BASE_OPTS, deepSummary: deepLegacy });
    expect(md).toContain('### The Opening Argument');
  });

  it('formats duration correctly for short episodes', () => {
    const md = summaryToMarkdown({
      episodeTitle: 'Short',
      podcastName: 'Pod',
      durationSeconds: 900, // 15 minutes
      quickSummary: QUICK,
    });
    expect(md).toContain('15m');
    expect(md).not.toContain('0h');
  });
});
